resource_types:
  - name: rss-resource
    type: docker-image
    source:
      repository: suhlig/concourse-rss-resource
      tag: latest

resources:
  - name: postgres-release-versions
    type: rss-resource
    source:
      url: https://www.postgresql.org/versions.rss

jobs:
  - name: monitor-postgres-releases
    plan:
    - get: postgres-release-versions
      trigger: true

    - task: alert
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: echo
          args: ["There is a new Postgres release"]
