#!/bin/bash -eu

fly --target lite login

fly \
  set-pipeline \
  -t lite \
  -p postgres-release-monitor \
  -c example/pipeline.yml

fly \
  unpause-pipeline \
  -t lite \
  -p postgres-release-monitor
