#!/bin/bash -eu

fly --target lite login

fly \
  set-pipeline \
  --target lite \
  --pipeline postgres-release-monitor-slack \
  --var "slack-webhook-url=${SLACK_WEBHOOK}" \
  --config example/pipeline-with-slack.yml

fly \
  unpause-pipeline \
  --target lite \
  --pipeline postgres-release-monitor-slack
