jobs:
  - name: test-latest-source
    plan:
      - get: latest-source
        trigger: true
      - task: run-tests
        file: latest-source/ci/tasks/run-tests.yml
        input_mapping: { source: latest-source }

  # Create a new tag in order to trigger this
  - name: test-and-ship-tag
    plan:
      - in_parallel:
        - get: tagged-commits
          trigger: true
        - get: latest-source
      - task: run-tests
        file: latest-source/ci/tasks/run-tests.yml # config comes from latest
        input_mapping: { source: tagged-commits } # code under test is the tagged source
      - task: build-image
        privileged: true
        file: tagged-commits/ci/tasks/build-oci-image.yml
        input_mapping: { source: tagged-commits }
      - load_var: image-version
        file: tagged-commits/.git/describe_ref # https://github.com/concourse/git-resource#additional-files-populated
      - put: docker-hub
        params:
          image: image/image.tar
          version: ((.:image-version))
          bump_aliases: true

resources:
  - name: latest-source
    type: git
    icon: github
    source: &git-source
      uri: git@github.com:suhlig/concourse-rss-resource.git
      private_key: ((github-ssh-key))

  - name: tagged-commits
    type: git
    icon: github
    source:
      <<: *git-source
      fetch_tags: true
      tag_filter: v*

  - name: docker-hub
    type: registry-image
    icon: docker
    source:
      repository: suhlig/concourse-rss-resource
      username: suhlig
      password: ((dockerhub-auth-token))
